{
    "name": "Lm_Zisterne_FHEM",
    "version": "0.0.1",
    "icon": "fab fa-battle-net",
    "category": "undefined",
    "author": "milode",
    "maintainers": [],
    "desc": "Abfrage des fuellstands der zisterne",
    "aliceMinVersion": "1.0.0-b1",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        ""
    ],
    "conditions": {
        "lang": [
            "en",
            "de"
        ],
        "asrArbitraryCapture": true
    }
}